[package]
name = "wren-rs"
version = "0.1.0"
authors = ["fanlia <3093932086@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
